version: '3'

volumes:
  post_service_local_postgres_data: {}
  post_service_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: post_service_local_django
    container_name: post_service_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi --reload
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: post_service_local_postgres
    container_name: post_service_local_postgres
    volumes:
      - post_service_local_postgres_data:/var/lib/postgresql/data
      - post_service_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
