# Generated by Django 4.1.6 on 2023-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_request",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
